kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ilert-kube-agent.fullname" . }}
  labels: 
    {{- include "ilert-kube-agent.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - nodes
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/logs
    verbs:
      - get
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - update
    resourceNames:
      - "{{ .Values.electionID }}"
  - apiGroups:
      - "ilert.com"
    resources:
      - incidents
    verbs:
      - create
      - update
      - get
      - delete
      - list
      - watch
