# Default values for ilert-kube-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ilert/ilert-kube-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1.4.0

config:
  settings:
    ## (REQUIRED) The iLert alert source api key
    # apiKey: <YOU-API-KEY>

    ## Path to a kubeconfig. Only required if out-of-cluster.
    # kubeconfig: "~/.kube/config"

    ## The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
    # master: ""

    ## The lease lock resource name
    electionID: ilert-kube-agent

    ## The metrics server port
    port: 9092

    ## The evaluation check interval e.g. resources check
    checkInterval: 30s

    log:
      ## Log level (debug, info, warn, error, fatal).
      level: info
      ## Enable json logs
      json: false

  alarms:
    pods:
      ## Enables all pod alarms
      enabled: false

      terminate:
        ## Enables terminate pod alarms
        enabled: true
        ## The pod terminate alarm incident priority
        priority: HIGH

      waiting:
        ## Enables waiting pod alarms
        enabled: true
        ## The pod waiting alarm incident priority
        priority: LOW

      restarts:
        ## Enables restarts pod alarms
        enabled: true
        ## The pod restarts alarm incident priority
        priority: LOW
        ## Pod restart threshold to alarm (min 1)
        threshold: 10

      resources:
        ## Enables resources pod alarms
        enabled: true
        ## The pod resources alarm incident priority
        priority: LOW
        ## The pod resources percentage threshold from 1 to 100
        threshold: 90

    nodes:
      ## Enables all pod alarms
      enabled: true

      terminate:
        ## Enables terminate node alarms
        enabled: true
        ## The node terminate alarm incident priority
        priority: HIGH

      resources:
        ## Enables resources node alarms
        enabled: true
        ## The node resources alarm incident priority
        priority: LOW
        ## The node resources percentage threshold from 1 to 100
        threshold: 90

  links:
    pods:
      ## Pods URL for the alarm-related incident. Your can use following mustache variables here: pod_namespace, pod_name, cluster_name
      # - name: Metrics
      #   href: "https://grafana.example.com/d/kubernetes/kubernetes-overview?var-Node=All&var-Pod={{pod_name}}"
      # - name: Logs
      #   href: "https://grafana.example.com/explore?left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Binstance%3D%5C%22{{pod_name}}%5C%22,namespace%3D%5C%22{{pod_namespace}}%5C%22%7D%22%7D%5D"
    nodes:
      ## Nodes URL for the alarm-related incident. Your can use following mustache variables here: node_name, cluster_name
      # - name: Metrics
      #   href: "https://grafana.example.com/d/kubernetes/kubernetes-overview?var-Node={{node_name}}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 50m
  #   memory: 32Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
