apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ilert-kube-agent.fullname" . }}
  labels: 
    {{- include "ilert-kube-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ilert-kube-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "ilert-kube-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}