apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ilert-kube-agent.fullname" . }}
  labels:
    {{- include "ilert-kube-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- $config := .Values.config -}}
{{- if not .Values.inClusterRoutesEnabled -}}
{{- $settings := omit .Values.config.settings "httpAuthorizationKey" -}}
{{- $config := set $config "settings" $settings -}}
{{- end }}
{{ toYaml $config | indent 4 }}