apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ilert-kube-agent.fullname" . }}
  labels:
    {{- include "ilert-kube-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}