apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: incidents.ilert.com
  labels:
    {{- include "ilert-kube-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: ilert.com
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
  names:
    plural: incidents
    singular: incident
    listKind: IncidentList
    kind: Incident
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["id"]
          properties:
            id:
              type: "integer"
              minimum: 0
            summary:
              type: "string"
            details:
              type: "string"
            type:
              type: "string"
